# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
  branches:
    include:
      - feature/SandeepDev  # Triggers pipeline automatically on changes in this branch

parameters:
  - name: environment
    displayName: Deployment Environment
    type: string
    default: 'nonprod'
    values:
      - nonprod
      - prod

variables:
  - name: SUBSCRIPTION
    value: 'ServiceConnection1'

  - name: RESOURCE_GROUP
    value: '460-ebcc6e24-deploy-a-node-js-app-to-a-deployment'

  - name: APP_SERVICE_APP_NAME
    value: 'webappwpwsszwb23aca'

  - name: SLOT_NAME
    value: 'dev'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build Job
        pool:
          name: 'Default'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              path: '$(Pipeline.Workspace)/.npm'
              cacheHitVar: 'CACHE_RESTORED'
            displayName: 'Cache npm dependencies'

          - script: npm install --verbose
            displayName: 'Install Dependencies'

          - script: npm test
            displayName: 'Run Tests'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

  - template: templates/deploy-template.yml
    parameters:
      environment: ${{ parameters.environment }}          

      
