trigger:
  branches:
    include:
      - feature/develop  # Triggers pipeline automatically on changes in this branch

parameters:
  - name: environment
    displayName: Deployment Environment
    type: string
    default: 'nonprod'
    values:
      - nonprod
      - prod

variables:
  SUBSCRIPTION: ${{ parameters.environment == 'nonprod' && 'ServiceConnection1' || 'ServiceConnection2' }}
  RESOURCE_GROUP: ${{ parameters.environment == 'nonprod' && 'RG-NonProd' || 'RG-Prod' }}
  APP_SERVICE_APP_NAME: ${{ parameters.environment == 'nonprod' && 'webapp-nonprod' || 'webapp-prod' }}

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build Job
        pool:
          name: 'Default'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              path: '$(Pipeline.Workspace)/.npm'
              cacheHitVar: 'CACHE_RESTORED'
            displayName: 'Cache npm dependencies'

          - script: npm install --verbose
            displayName: 'Install Dependencies'

          - script: npm test
            displayName: 'Run Tests'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          -
